services:
  mongo:
    image: mongo:7.0
    container_name: securecollab-mongodb
    ports:
      - "27017:27017"
    volumes:
      - securecollab_mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: securecollab

volumes:
  securecollab_mongodb_data:
